### ISSUE TITLE
webpack2 problems

### ISSUE THREAD

**Issue by cescoferraro** [Quramy/typed-css-modules#19]
Thanks for the library!

### Originally posted https://github.com/olegstepura/typed-css-modules-loader/issues/10

Stack
```
ERROR in ./~/css-loader?sourceMap&modules&importLoaders=1&localIdentName=[path]___[name]__[local]___[hash:base64:5!./~/sass-loader?sourceMap!./~/typed-css-modules!./~/sass-loader!./src/sass/main.scss
Module build failed: TypeError: Cannot call a class as a function
    at _classCallCheck (/home/cescoferraro/code/go/src/github.com/cescoferraro/spotify/node_modules/typed-css-modules/lib/dtsCreator.js:46:99)
    at Object.DtsCreator (/home/cescoferraro/code/go/src/github.com/cescoferraro/spotify/node_modules/typed-css-modules/lib/dtsCreator.js:123:5)
 @ ./src/sass/main.scss 4:14-312
 @ ./src/ts/shell.tsx
 @ ./src/ts/app.tsx
```

preloader
```
{
            enforce: 'pre',
            test: /\.scss$/,
            exclude: /node_modules/,
            loaders: ['typed-css-modules', 'sass-loader']
        }
```

**Comment by scriby** [comment]
Correct me if I'm wrong, but I don't think typed-css-modules is a webpack loader. I think you're going to have to write some glue code to connect the webpack loader interface to typed-css-modules.

**Comment by Eugen-Ask** [comment]
I have the same issue

**Comment by Eugen-Ask** [comment]
I solved the problem: just changed `typed-css-modules` to `typed-css-modules-loader` like this
```
{
        test:   /\.sss/,
        use: [
          'style-loader',
          'css-loader?modules&importLoaders=1',
          'typed-css-modules-loader',
          'postcss-loader?parser=sugarss',
        ],
      },
```

**Comment by cameron-martin** [comment]
In webpack 2, they stopped automatically adding the `-loader` suffix to loader names.
