### ISSUE TITLE
Cannot find module 'gaze'

### ISSUE THREAD

**Issue by testerez** [Quramy/typed-css-modules#9]
I'm just trying to run the example with `cd example && npm i && npm start` but I'm getting this error:
```
Error: Cannot find module 'gaze'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/testerez/projects/trash/typed-css-modules/lib/cli.js:10:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

I tried after `npm i gaze`, same error...

Using npm 3.8.5 and node v4.4.2

**Comment by Quramy** [comment]
Please execute `npm i` at the `typed-css-modules` dir.

**Comment by testerez** [comment]
I worked, thanks!
